name: forisa_package
description: Forisa Package
version: 2.0.1
author: Edward Reynara <edwardreynara@gmail.com>
homepage: https://github.com/edward-reynara/forisa_package.git

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.6.0
  auto_size_text: ^3.0.0
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  package_info_plus: ^4.2.0
  image_picker: ^1.0.7
  flutter_datetime_picker_plus: ^2.1.0
#  connectivity_plus: ^3.0.6
  android_id: ^0.3.6
  device_info_plus: ^9.1.2
#  platform_device_id: ^1.0.1
#  custom_platform_device_id: ^1.0.8
  platform_device_id_v3: ^1.0.0
  shimmer: ^3.0.0
  flutter_typeahead: ^4.8.0
  photo_view: ^0.15.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.0
  #  flare_flutter: ^3.0.2
  #nullsafety
  random_color: ^1.0.6-nullsafety

  # Git
  flare_flutter:
    git:
      url: https://github.com/mbfakourii/Flare-Flutter.git
      path: flare_flutter
      ref: remove_hashValues

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
